# general settings
name: train_JARNet_LAP_20240114
model_type: ImageMlossFlowModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: LAPDataSet
    dataroot_gt: ~ # Please fill out the path to the LAP training dataset.
    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4

    mini_batch_sizes: [4]   
    iters: [450000]
    gt_size: 128   
    gt_sizes: [128]

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: LAPDataSet
    dataroot_gt: ~ # Please fill out the path to the LAP evaluation dataset.
    io_backend:
      type: disk

network_g:
  type: JARNet
  img_channel: 1
  width: 32
  middle_blk_num: 4
  enc_blk_nums: [4, 4, 4, 4]
  dec_blk_nums: [4, 4, 4, 4] 
  window_size_e_fft: [64, -1, -1, -1]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 450000 
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 450000
    eta_min: !!float 1e-7 

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-3
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

  flow_opt:
    type: PerceptualLoss
    loss_weight: 0.0001
    reduction: mean

  msfr_opt:
    type: FFTLoss
    loss_weight: 0.1
    reduction: mean

  flow_weight: 0.1

# validation settings
val:
  window_size: 8
  val_freq: !!float 5e4
  save_img: false
  save_last_img: true
  rgb2bgr: false
  use_image: true

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
